server:
  port: 9102
spring:
  application:
    name: shop-actuator-admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
  jmx:
    default-domain: shop-actuator-admin-9102