spring:
  application:
    name: shop-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
  jmx:
    default-domain: shop-consumer
management:
  endpoints:
    web:
      exposure:
        include: '*'